### ISSUE TITLE
Can't get the results

### ISSUE THREAD

**Issue by kush80510** [AJaySi/AI-Writer#113]
I am a non-coder, so it took a lot of time firstly to get the website, but did it with help of chatgpt.
The issue is whenever i tried to create a blog post or production descreption it doesn't give the final output. 
Have attached ss of the issue. 
![Screenshot 2024-08-24 160607](https://github.com/user-attachments/assets/dd603948-9d6f-4d94-9e61-33982b7ecf41)
![Screenshot 2024-08-24 160659](https://github.com/user-attachments/assets/81f8daff-e07a-414a-8ce1-ce295322ccfc)
![Screenshot 2024-08-24 160711](https://github.com/user-attachments/assets/cd4ba2ac-8bd7-4828-823e-94c9bdecb507)

**Comment by AJaySi** [comment]
@kush80510 
You closed the issue, although i hope the issue was solved.
Sorry, for the trouble getting started with alwrity app. 

It will help the community if you provide feedback on getting started, we will improve on it.
Feel free to open issues. Thank you for attaching the screenshots.
Regards.
