### ISSUE TITLE
Alwrity AI story writer

### ISSUE THREAD

**Issue by AJaySi** [AJaySi/AI-Writer#31]
1). Add support for AI story writer or generator.
2). It should produce long form content, more than 5k words atleast.
3). Utilise iterative generation and prompt chaining.
https://github.com/google-gemini/cookbook/blob/main/examples/Story_Writing_with_Prompt_Chaining.ipynb

**Comment by AJaySi** [comment]
Latest code has AI story writer as feature of Alwrity.
Needs improvements.

**Comment by DikshaDisciplines** [comment]
Hi @uniqueumesh, 
Sharing enhancement notes for our review on [Story Writer](https://www.alwrity.com/ai-story-writer). 
+ Content publishing

Prompt : How can i improve page (https://www.alwrity.com/ai-story-writer) , as per SEO?

Aim
To improve Website page for SEO (Search Engine Optimization) and boost its visibility on search engines, technical optimization, content depth, and user experience (UX).
Actionable improvements:

Currently, the page does a great job outlining features and background logic, but it suffers from a few critical structural, copy, and performance bottlenecks that hurt its search engine visibility.

1. Fix Critical Heading Structure (The H1 Problem)
Search engines use <h1> tags to understand the primary topic of a page. You should only ever have one <h1> tag per page. Currently, your page uses multiple H1s:
<h1>AI Story Writer & Novel Generator</h1>
<h1>Try Our AI Story Writer Here!⬇️</h1>
<h1>AI Story Writers: A Tool, Not a Replacement</h1>

Solution:
Keep <h1>AI Story Writer & Novel Generator</h1> at the very top.
Demote the other two to <h2> or <h3> tags.

2. Rework the App Embed & UX Signals
Google places massive weight on User Experience (UX) signals like dwell time and page stability.

The "Duct Tape" Copy: Your text reads: "We're so sorry about the loading time, 🚧. You see, it's free, so we're basically using duct tape and prayers..." While humorous, this tells search crawlers and users that the page has poor performance, leading to quick bounces. Change this to something authoritative, like: "Loading your AI Story Framework... Please give our server a brief moment to initialize your sandbox."

Iframe Optimization: Your interactive app runs inside an iframe. If the iframe loads slowly, it tanks your Core Web Vitals (a major Google ranking factor). Ensure your iframes are set to lazy-load by adding loading="lazy" to the code, and explicitly define width and height attributes to prevent layout shifts.

3. On-Page Keyword & Copy Tuning
While you target "AI Story Writer," you are missing out on valuable long-tail semantic variations (LSI keywords) that authors search for.
Title Tag & Meta Description: Ensure your meta title explicitly highlights the "No Signup / Free" elements to steal clicks from competitors.

Target Meta Title: Free AI Story Writer & Novel Generator (No Signup) | ALwrity

Inject Search Variations: Integrate these terms naturally into your subheadings and body text:

AI novel generator

Plot generator free

AI fiction writer

How to overcome writer's block with AI

4. Implement FAQ Schema Markup
You already have a fantastic FAQ section at the bottom of the page. However, it is just plain text.

Solution:
Convert these FAQs into JSON-LD FAQ Schema and inject it into the page header. This allows Google to display your FAQs directly on the search engine results page (SERP) as rich snippets, effectively doubling your organic screen real estate.

5. Clean Up Broken & Outdated Elements
Technical health is foundational to SEO ranking.

Update the Copyright Footer: Your footer states © 2025 by alwrity.com. Keeping it updated to the current year (2026) tells both search engines and users that the site is actively maintained.

Fix Image Alt Text: Your internal blog links use generic alt text like ![Long Form AI story writing]. Change these to descriptive text like alt="Tutorial graph showing long form AI story writing workflow" to capture Google Image search traffic.

Anchor Text Optimization: In your "Related AI Writers" section, change generic phrases into descriptive keywords. Instead of a separate block of text, embed the hyperlinks directly into the key terms, like [AI Letter Writer](https://www.alwrity.com/ai-story-writer) and [AI Essay Writer](https://www.alwrity.com/ai-story-writer)

**Comment by uniqueumesh** [comment]
## 1. Functionality (is it working) 

### Links & Buttons problem:
- "**Beta app.io link**" is broken. Clicking it leads to a "This site can’t be reached" error page.
- "**Explore All Writer**" button mistakenly routes users to the [home page](https://www.alwrity.com/) instead of the designated writers page.

### Solution:
- Remove the "**Beta app.io link**" text and link entirely, as we are not offering a separate story generator tool right now.
- Update the **Explore All Writer** button to point directly to the **[AI Writers](https://www.alwrity.com/ai-writers)** directory so it navigate to the correct page.

## 2. Visual Style & Ease of Use (UI/UX)

### Design (UI) problem:
- **H1 Title**:  The title is structurally crowded by surrounding elements and lack of breathing room required to look clean and modern user experience.
- **H2 Title**: The headline is overly verbose and reads like instruction manual sentence ("Key Features and How to Use Our Story Writing App Below").
- **Tool instruction section**: The long, manual step-by-step guide is looks like an unformatted, text-heavy blog post. 

### Solution:
- **H1 Title**: Increase padding/margin around the header to give visual separation.
- **H2 Title**: Shorten into a punchy, benifit-driven header that aligns with modern UI design (e.g. "How it Works" or "Craft Your Story in Simple Steps")
- **Tool instruction section**: Style this area cleanly with proper spacing, icons,or a card layout. If designed  beautifully, users will gladly read through the tips while the Streamlit iframe builds itself in the background.

**UI Mock Example:**

<img width="1024" height="664" alt="Image" src="https://github.com/user-attachments/assets/dedbf2cf-fe7e-4ba1-a6f7-74a3b1fd75d3" />

---

**Note**: The UI improvements apply to the section above the app interface on the [AI Story Generator](https://www.alwrity.com/ai-story-writer) page, while the link and button fixes target the section below the tool.

**Comment by uniqueumesh** [comment]
## 2. Visual Style & Ease of Use (UI/UX)

### Design (UI) problem:
- **Outdated & Cluttered Layout**: There are currently three separate containers featuring outdated, "2012-style" 3D tool icons. This creates a cluttered, unprofessional look and negatively impacts page loading speeds (Core Web Vitals).
- **Low Contextual Relevance**: We are displaying corporate and journalism utilities (e.g., business letter writers, news writers) that do not align with the intent or interests of an AI Story Writer user.

### Proposed Solution: 
- **Modern UI Integration**: Replace the current containers with a clean, modern iframe using Wix custom code, matching the layout design seen on the main [AI Writers](https://www.alwrity.com/ai-story-writer) directory page.
- **Contextual Tool Curation**: Select 4 highly relevant tools that naturally extend a creative writer's workflow. These should be featured directly below the story writer app, ordered by behavioral relevance:

#### 1. AI Blog Writer or Outline Generator
- **Why it fits**: Creative writers often structure multi-chapter novels or serialized fiction. A tool that aids in mapping narrative frameworks and initial drafts is highly relevant.
- **The Frame**: Position it as a solution for structuring complex creative concepts and long-form narrative drafts.

#### 2. YouTube Video to Blog
- **Why it fits**: Modern storytelling is multimedia-driven. Authors, playwrights, and scriptwriters frequently need to convert spoken-word audio, audio transcripts, or video concepts into written prose.
- **The Frame**: Highlight its ability to instantly convert audio/video storytelling transcripts into beautifully formatted text.

#### 3. LinkedIn Blog Writer
- **Why it fits**: Independent authors must build a personal brand to market their books. They need to share their writing updates and creative journeys without adopting a dry, overly corporate tone.
- **The Frame**: Pitch it as a tool to transform creative storytelling concepts into engaging, professional social updates.

#### 4. Product Description Suite
- **Why it fits**: Self-published authors and independent creators sell digital books, physical copies, and merchandise online. They require high-converting, benefit-driven copy to pitch their work.
- **The Frame**: Position it as a creative copywriting assistant to help authors market and describe their books or chapters effectively.

### Suggested 4-Column Editorial Layout
- To optimize user engagement and maximize click-through rates (CTR), we should clean up the call-to-actions. We should replace the bulky, 3D metallic buttons with flat, unified iconography and use outcome-focused microcopy.

| Tool Name | Action-Oriented Editorial Copy |
|-----------|-------------------------------|
| Blog or Outline Generator | Structuring a complex project? Move from an initial narrative concept to a fully organized, long-form draft seamlessly. |
| Video to Text Converter | Turn spoken narratives, video concepts, or audio transcripts into beautifully formatted, ready-to-read prose. |
| Social Insight Writer | Share your creative journey. Translate your storytelling ideas into engaging, professional updates for your feed. |
| Creative Pitch Builder | Ready to share your work? Draft compelling, benefit-first descriptions to pitch your stories and books to readers. |

**Comment by AJaySi** [comment]
I am not able to follow these issues.
You both are putting lot of AI Slop here.

- Issue should communicate what we are doing for that issue and how much work is done.
-  What are we implementing, how much of implementation is done ?
- If we keep adding new things to existing issues, the issue will never get over.
- If we keep asking AI, it will continue to give "Ideas" till 2047, when india will become a superpower.
- Its getting difficult to follow what is going on
- We need to have estimation and finish off issues and start new issue for new requirements.
@uniqueumesh @DikshaDisciplines 

- For example, Creating One issue on "Improve blog writer" is a BAD issue, as its generic and there can be hundreds of issues on improving blog writer. Instead we should open a targeted issue like 'Blog Writer page Loading Speed is slow' and "Blog Writer introduction paragraph needs improvement" and another issue "The blog writer generated outline quality is not accurate" etc etc etc and then we have a label as "Blog Writer"

**Comment by uniqueumesh** [comment]
@AJaySi @DikshaDisciplines 

@AJaySi Yes, I totally agree with your thought.

As we have discussed in the [Website Tester Guide: Testing & Enhancement Process Plan](https://drive.google.com/file/d/1X-rY8MrALAtMbqXnQuV1KCK7Ti-T8kDM/view), I think @DikshaDisciplines had mentioned that we have to first document all the issues and solutions for the team review and then implement them. I am just following the plan we had discussed.

We can make changes to the further testing plan and implementation. If there are any examples for reference, then please share that will help me understand how it's done.

regards,

**Comment by AJaySi** [comment]
Like issue 566 is a targeted change and we know what is being target, what will be done. So, its fine.

@DikshaDisciplines : We can use your github projects for this. Also use github discussions for ideas and plannign ?

I am also thinking of using github discussions like: https://github.com/AJaySi/ALwrity/discussions
Review the discussions, we can use this for ideas and improvements on one app like story writer and this present issue.

- We can then make small issues from the github discussion points.

- We should then refer to that discussions in all related issues, we are working on.

- Of course, there can be small issues, that Dont need discussions, like bugs, defects etc, but maybe new feature request or changes to the whole app, require a discussion.

- Also, understanding and using "Create sub-Issues" 

1. **Move Brainstorming to Discussions:** Take the UI/UX enhancement concepts and SEO suggestions, Diksha and you discussed and move them to a new thread under **GitHub Discussions** (or a dedicated GitHub Project) for long-term planning.

2. **Break Down into Small, Targeted Issues:** From those discussions, we will spin out tight, isolated issues (e.g., *"Fix broken Beta app.io link on Story Writer page"*, *"Update copyright footer to 2026"*, or *"Implement FAQ Schema Markup"*).

3. **Current Scope for #31:** For this specific issue, let's focus purely on finalizing the core implementation of the long-form story writer feature. I think, we should target this, at the end, as getting this right will also give us long form blog writer. So, two features in one, but first lets get the "Low Hanging Fruits" issues fixed first.
 

What do you guys think ?

**Comment by DikshaDisciplines** [comment]
@uniqueumesh  Discussed points  
- how to change URL slug with new reached key word (https://www.alwrity.com/ai-story-writer) (TBD) 

- Correct the Blog Category Name on menu and all important pages. From 'AI story writer' to 'AI story generator'.

- Sider display of suggested Blog Topic for story generator

- Story generator Application testing (TBD) 

- Review of Alwrity website articles for Content cannibalization (tbd)

**Comment by uniqueumesh** [comment]
### Progress Update: AI Story Generator Enhancements

I've completed the implementation of the reviewed landing page content alongside the following updates:

| Feature / Task | Status | Notes |
| :--- | :--- | :--- |
| **Category Name Correction** | ✅ Done | Updated from 'AI story writer' to 'AI story generator' across the menu and core pages. |
| **App Testing** | ✅ Done | Story generator application testing is complete. |
| **Sidebar Display** | ✅ Done | Suggested blog topics are now visible in the sidebar. |
| **URL Slug Transition** | ⏳ TBD | Still investigating the best way to handle the keyword transition for `/ai-story-writer`. |
| **Content Cannibalization Review** | ⏳ TBD | Website article audit is pending. |

@AJaySi @DikshaDisciplines — I am closing this issue as the core enhancements are done. We can tackle the longer-process TBD tasks later in separate, isolated issues.

regards,

**Comment by AJaySi** [comment]
@uniqueumesh Great. Lets close this and tackle long form later.
