### ISSUE TITLE
Streamlit-ting Alwrity

### ISSUE THREAD

**Issue by AJaySi** [AJaySi/AI-Writer#7]
### Discussed in https://github.com/AJaySi/AI-Blog-Writer/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **AJaySi** March 15, 2024</sup>
I will be soon ditching the CLI and moving to Streamlit App version.
Also, I can host that app on streamlit cloud, making installation obsolete for alwrity.</div>

**Comment by AJaySi** [comment]
Not a priority for me, right now.
You can contribute Or if in hurry, there are many paid versions you can try.

**Comment by umesh070** [comment]
@thehaseebhassan

It's important to remember to be considerate and understanding when communicating with others, especially when they are working on something independently. It seems like you may have been eagerly awaiting the streamlit version, but it's essential to approach the situation with patience and kindness. @AJaySi is working on this tool alone, without a team to assist, so it's understandable that their priorities might differ. Instead of expressing frustration, perhaps a more supportive and encouraging tone would be more appropriate.

**Comment by thehaseebhassan** [comment]
@umesh070 

I just asked him that it's been 3 weeks since you opened the issue. He cleared that it's not a priority right now.

I didn't mean to be discouraging, cheers!

**Comment by AJaySi** [comment]
@thehaseebhassan @umesh070 

Please visit alwrity.com , there are online AI tools there.
The commandline one has much features. 

I am closing this for now, as we will continue making standalone AI content tools and mostly support commandline version. Its mostly due to resources constraints and not sure of the directions to take.
